source "https://rubygems.org"  # where gems will be downloaded from
ruby "3.1.2"

gem 'pry', '~> 0.14.1'
gem 'debug', '~> 1.6', '>= 1.6.2'

# group :development do
#     gem "debug", platforms: %i[ mri mingw x64_mingw ]
#     gem 'faker', '~> 1.6', '>= 1.6.6', require: false
# end

